version: '3.1'

services:

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "-A md5"
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  etl:
    build: .
    command: python3 /mnt/scripts/job.py
    volumes:
      - .:/mnt/scripts
    depends_on:
      - db
